/* GENERAL */
export const VALUE_CHANGE = 'VALUE_CHANGE_';
export const GENERAL_ERROR = 'GENERAL_ERROR_';

/* INTRO */
export const INITIALIZE_APP = 'INITIALIZE_APP';
export const INITIALIZE_APP_SUCCESS = 'INITIALIZE_APP_SUCCESS';

/* SETTINGS */
export const INITIALIZE_SETTINGS = 'INITIALIZE_SETTINGS';
export const INITIALIZE_SETTINGS_SUCCESS = 'INITIALIZE_SETTINGS_SUCCESS';
export const INITIALIZE_SETTINGS_FAILED = 'INITIALIZE_SETTINGS_FAILED';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_FAILED = 'SAVE_SETTINGS_FAILED';
export const CANCEL_SETTINGS = 'CANCEL_SETTINGS';
export const CANCEL_SETTINGS_SUCCESS = 'CANCEL_SETTINGS_SUCCESS';
export const CHANGE_PATH = 'CHANGE_PATH';
export const CHANGE_PATH_SUCCESS = 'CHANGE_PATH_SUCCESS';
export const VALUE_CHANGE_SETTINGS = 'VALUE_CHANGE_SETTINGS';

/* STRUCTURE */
export const INITIALIZE_STRUCTURE = 'INITIALIZE_STRUCTURE';
export const INITIALIZE_STRUCTURE_SUCCESS = 'INITIALIZE_STRUCTURE_SUCCESS';
export const INITIALIZE_STRUCTURE_FAILED = 'INITIALIZE_STRUCTURE_FAILED';
export const SAVE_STRUCTURE = 'SAVE_STRUCTURE';
export const SAVE_STRUCTURE_SUCCESS = 'SAVE_STRUCTURE_SUCCESS';
export const SAVE_STRUCTURE_FAILED = 'SAVE_STRUCTURE_FAILED';
export const MANIPULATE_STRUCTURE_HEADER = 'MANIPULATE_STRUCTURE_HEADER';
export const MANIPULATE_STRUCTURE_FIELD = 'MANIPULATE_STRUCTURE_FIELD';

/* MIGRATION */
export const INITIALIZE_MIGRATION = 'INITIALIZE_MIGRATION';
export const INITIALIZE_MIGRATION_SUCCESS = 'INITIALIZE_MIGRATION_SUCCESS';
export const INITIALIZE_MIGRATION_FAILED = 'INITIALIZE_MIGRATION_FAILED';
export const SAVE_MIGRATION = 'SAVE_MIGRATION';
export const SAVE_MIGRATION_SUCCESS = 'SAVE_MIGRATION_SUCCESS';
