/* GENERAL */
export const VALUE_CHANGE = 'VALUE_CHANGE_';
export const GENERAL_ERROR = 'GENERAL_ERROR_';

/* INTRO */
export const INITIALIZE_APP = 'INITIALIZE_APP';
export const INITIALIZE_APP_SUCCESS = 'INITIALIZE_APP_SUCCESS';

/* SETTINGS */
export const INITIALIZE_SETTINGS = 'INITIALIZE_SETTINGS';
export const INITIALIZE_SETTINGS_SUCCESS = 'INITIALIZE_SETTINGS_SUCCESS';
export const INITIALIZE_SETTINGS_FAILED = 'INITIALIZE_SETTINGS_FAILED';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SET_DEFAULTS = 'SET_DEFAULTS';
export const CHANGE_PATH = 'CHANGE_PATH';

/* STRUCTURE */
export const INITIALIZE_STRUCTURE = 'INITIALIZE_STRUCTURE';
export const INITIALIZE_STRUCTURE_SUCCESS = 'INITIALIZE_STRUCTURE_SUCCESS';
export const INITIALIZE_STRUCTURE_FAILED = 'INITIALIZE_STRUCTURE_FAILED';
export const SAVE_STRUCTURE = 'SAVE_STRUCTURE';
export const SAVE_STRUCTURE_SUCCESS = 'SAVE_STRUCTURE_SUCCESS';
