/* GENERAL */
export const VALUE_CHANGE = 'VALUE_CHANGE_';
export const MULTI_FORM_VALUE_CHANGE = 'MULTI_FORM_VALUE_CHANGE_';
export const LOCALIZED_VALUE_CHANGE = 'LOCALIZED_VALUE_CHANGE_';
export const GENERAL_ERROR = 'GENERAL_ERROR_';

/* SETTINGS */
export const THEME = 'THEME';

/* TEST */
export const LOG_MESSAGE = 'LOG_MESSAGE';
export const LOG_MESSAGE_SUCCESS = 'LOG_MESSAGE_SUCCESS';
